service:
  name: skynet
  environment: ${file(env.yml):${self:custom.stage}}

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  tracing: true
  iamRoleStatements:
    - Effect: Allow
      Resource: arn:aws:ssm:*:*:parameter/*
      Action:
        - ssm:GetParameter
        - ssm:PutParameter
    - Effect: Allow
      Resource: "*"
      Action: 
        - organizations:ListAccounts
    - Effect: Allow
      Resource: "*"
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords

functions:
  account_reaper:
    handler: handler.main
    events:
      - schedule: rate(30 days)
